#!/usr/bin/env python3
"""
Velgard European Financing Radar — Daily Fetch Script
Runs via GitHub Actions every morning.
Updates data/opportunities.json and sends email digest.
"""

import json
import os
import smtplib
import urllib.request
import urllib.parse
import uuid
from datetime import datetime, timezone, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
NOTIFY_EMAIL   = "ivan.radvak@velgard.eu"
SMTP_HOST      = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT      = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER      = os.getenv("SMTP_USER", "")       # set as GitHub secret
SMTP_PASS      = os.getenv("SMTP_PASS", "")       # set as GitHub secret

KEYWORDS       = ["AI", "artificial intelligence", "cybersecurity", "cyber security",
                  "deep tech", "deeptech", "digital security", "machine learning",
                  "data security", "privacy", "encryption", "autonomous systems"]

DATA_FILE      = Path(__file__).parent.parent / "data" / "opportunities.json"
DATA_JS_FILE   = Path(__file__).parent.parent / "data" / "data.js"
CLOSING_DAYS   = 30   # flag as closing soon within N days

# Hand-curated entries below are transcribed from official programme pages and
# they rot: calls close, deadlines move, whole programmes wind down. Every entry
# therefore carries verified_on, and anything not re-confirmed within this window
# is dropped rather than published as if it were still current. Prefer adding a
# live source over adding a hardcoded entry.
STALE_AFTER_DAYS = 75

# ── Helpers ───────────────────────────────────────────────────────────────────
TODAY_ISO = datetime.now(timezone.utc).strftime("%Y-%m-%d")

def days_until(date_str: str) -> int:
    d = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
    return (d.replace(tzinfo=timezone.utc) - datetime.now(timezone.utc)).days

def days_since(date_str: str) -> int:
    """Days elapsed since an ISO date. Returns a large number if unparseable."""
    try:
        d = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        if d.tzinfo is None:
            d = d.replace(tzinfo=timezone.utc)
        return (datetime.now(timezone.utc) - d).days
    except Exception:
        return 10**6

def is_relevant(text: str) -> bool:
    text_lower = text.lower()
    return any(kw.lower() in text_lower for kw in KEYWORDS)

def load_existing() -> dict:
    if DATA_FILE.exists():
        with open(DATA_FILE, encoding="utf-8") as f:
            return json.load(f)
    return {"last_updated": "", "opportunities": []}

def save_data(data: dict):
    data["last_updated"] = datetime.now(timezone.utc).isoformat()
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    # Also write data.js so index.html works when opened directly (file://)
    with open(DATA_JS_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by fetch_opportunities.py — do not edit manually\n")
        f.write("window.RADAR_DATA = ")
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write(";\n")
    print(f"✓ Saved {len(data['opportunities'])} opportunities")

# ── EU Funding & Tenders Portal ───────────────────────────────────────────────
SEDIA_URL   = "https://api.tech.ec.europa.eu/search-api/prod/rest/search"
SEDIA_PAGES = 3     # ~100 hits/page; heavy duplication, so a few pages is plenty

# type 1 = grant topics (type 0 is portal support/Q&A pages, which are noise).
# status 31094501 = forthcoming, 31094502 = open, 31094503 = closed. The status
# codes alone are not trustworthy — records tagged "open" still carry deadlines
# from 2021 — so the real currency check is done client-side on deadlineDate.
SEDIA_QUERY = {"bool": {"must": [
    {"terms": {"type": ["1"]}},
    {"terms": {"status": ["31094501", "31094502"]}},
]}}

def _sedia_request(text: str, page: int, page_size: int = 100):
    """One SEDIA search call.

    The endpoint rejects GET with 405, and silently ignores `query` when it is
    passed as a plain form field or in the query string — a request built that
    way returns millions of unfiltered rows rather than an error. It is only
    honoured as a multipart part explicitly typed application/json, so the body
    is assembled by hand here (stdlib only: the workflow pip-installs nothing).
    """
    qs = urllib.parse.urlencode({
        "apiKey": "SEDIA", "text": text,
        "pageSize": str(page_size), "pageNumber": str(page),
    })
    boundary = uuid.uuid4().hex
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="query"\r\n'
        f"Content-Type: application/json\r\n\r\n"
        f"{json.dumps(SEDIA_QUERY)}\r\n"
        f"--{boundary}--\r\n"
    ).encode("utf-8")
    req = urllib.request.Request(
        SEDIA_URL + "?" + qs, data=body, method="POST",
        headers={"Accept": "application/json",
                 "Content-Type": f"multipart/form-data; boundary={boundary}"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())

def fetch_eu_portal() -> list:
    """Open, Velgard-relevant grant topics from the EU Funding & Tenders portal.

    Results come back relevance-ranked; sorting by deadline instead just surfaces
    whichever calls happen to run furthest into the future. Each page repeats the
    same topics many times over (~10 unique per 100 rows), so identifiers are
    deduplicated, and every row is checked client-side for a future deadline and
    a keyword match before it is accepted.
    """
    def first(lst, fallback=""):
        return lst[0] if lst else fallback

    results, seen = [], set()
    try:
        for page in range(1, SEDIA_PAGES + 1):
            data = _sedia_request("artificial intelligence cybersecurity", page)
            rows = data.get("results") or []
            if not rows:
                break

            for item in rows:
                md = item.get("metadata", {})
                opp_id = first(md.get("identifier") or []) or item.get("id", "")
                if not opp_id or opp_id in seen:
                    continue
                seen.add(opp_id)

                deadline_raw = first(md.get("deadlineDate") or [])
                deadline = deadline_raw[:10] if deadline_raw else ""
                if not deadline or days_until(deadline) <= 0:
                    continue   # no deadline, or already closed

                title = first(md.get("title") or [])
                # The portal has no description field; the readable blurb is the
                # top-level summary, which falls back to the indexed content.
                desc = (item.get("summary") or item.get("content") or "").strip()
                if not is_relevant(f"{title} {desc}"):
                    continue

                combined = f"{title} {desc}".lower()
                categories = []
                if "artificial intelligence" in combined or " ai " in combined:
                    categories.append("AI")
                if "cybersecurity" in combined or "cyber security" in combined:
                    categories.append("cybersecurity")
                if "deep tech" in combined or "deeptech" in combined:
                    categories.append("deep tech")
                if not categories:
                    categories = ["deep tech"]

                # programmeName does not exist on these records; callTitle is the
                # human-readable cluster (e.g. "ENERGY") and typesOfAction the
                # instrument (e.g. "HORIZON Innovation Actions").
                call_title = first(md.get("callTitle") or [])
                action     = first(md.get("typesOfAction") or [])
                programme  = " — ".join(p for p in (action, call_title) if p) or "Horizon Europe"

                results.append({
                    "id": opp_id,
                    "title": title,
                    "source": "EIC" if "EIC" in opp_id.upper() else "EU Funding Portal",
                    "programme": programme,
                    "category": categories,
                    "status": "open",
                    "open_date": first(md.get("startDate") or [])[:10],
                    "deadline": deadline,
                    "budget": "See call page",
                    "description": (desc[:400] + "...") if len(desc) > 400 else desc,
                    "url": ("https://ec.europa.eu/info/funding-tenders/opportunities"
                            f"/portal/screen/opportunities/topic-details/{opp_id}"),
                    "tags": ["consortium", "EU"],
                    "verified_on": TODAY_ISO,   # seen live in the portal just now
                    "is_new": False,
                    "closing_soon": False,
                })
    except Exception as e:
        print(f"⚠ EU Portal fetch error: {e}")

    print(f"  EU Portal: {len(results)} relevant results ({len(seen)} topics examined)")
    return results

# ── EIC specific ──────────────────────────────────────────────────────────────
EIC_HARDCODED = [
    {
        "id": "HORIZON-EIC-2026-ACCELERATOR",
        "title": "EIC Accelerator 2026 — Open Call",
        "source": "EIC",
        "programme": "Horizon Europe — EIC",
        "category": ["AI", "cybersecurity", "deep tech"],
        "status": "open",
        "open_date": "2026-01-01",
        "deadline": "2026-09-02",
        "budget": "Up to €2.5M grant + up to €10M investment (blended finance)",
        "description": "EIC Accelerator supports startups and SMEs developing breakthrough innovations at TRL 6-8. Six cut-off dates per year; next cut-off 2 September 2026. 2026 budget: €414M (Open) + €220M (Challenges). Slovak companies fully eligible.",
        "url": "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
        "tags": ["SME", "startup", "equity", "blended finance"],
        "verified_on": "2026-08-26",
        "is_new": False,
        "closing_soon": False,
    },
    {
        "id": "HORIZON-EIC-2026-PATHFINDER-CHALLENGES",
        "title": "EIC Pathfinder Challenges 2026",
        "source": "EIC",
        "programme": "Horizon Europe — EIC",
        "category": ["AI", "deep tech"],
        "status": "open",
        "open_date": "2026-01-15",
        "deadline": "2026-10-28",
        "budget": "Up to €4M grant (2026 budget: €96M)",
        "description": "EIC Pathfinder Challenges funds visionary research on radical new technologies within defined thematic areas. AI foundations, advanced security, and novel computing paradigms are eligible themes. Note: EIC Pathfinder Open 2026 (separate track) already closed on 12 May 2026.",
        "url": "https://eic.ec.europa.eu/eic-funding-opportunities/eic-pathfinder_en",
        "tags": ["research", "early-stage", "TRL1-4"],
        "verified_on": "2026-08-26",
        "is_new": False,
        "closing_soon": False,
    },
]

# ── NGI Cascade calls ─────────────────────────────────────────────────────────
# Verified 2026-08-26: the NGI initiative is winding down and ngi.eu states
# "All the NGI projects are ending and there are no other calls available at the
# moment." The final NGI Zero Commons Fund call closed 2026-06-01; Taler and
# Fediversity closed 2026-08-01. NLnet has paused submissions while it launches
# successor programmes (Restack, CodeSupply, ELFA) under the Open Internet Stack
# umbrella — no concrete calls or deadlines announced yet. Re-add only once a
# successor call is actually open, with its real deadline.
NGI_CALLS: list = []

# ── Slovak calls ──────────────────────────────────────────────────────────────
# Verified 2026-08-26: no SIEA voucher call could be confirmed as open with a
# real deadline. Digital vouchers (09I02-03-V04) closed 2023-11-24. The 2026
# innovation-voucher sub-calls (progressive/dual-use technologies) had their
# deadline extended only to 2026-06-30, now passed, and SIEA reports the
# allocation as strained/exhausted. The previous "2026-12-31" deadline here was
# not sourced from any call document. Re-add per specific sub-call, with its own
# id and real deadline, rather than as one catch-all "vouchers" entry.
SLOVAK_CALLS: list = []

# ── Other European calls ──────────────────────────────────────────────────────
OTHER_CALLS = [
    {
        "id": "EUROSTARS-2026-S2",
        "title": "Eurostars 2026 Call 11 — International R&D Collaboration",
        "source": "EU Funding Portal",
        "programme": "Eurostars / EUREKA",
        "category": ["AI", "cybersecurity", "deep tech"],
        "status": "open",
        "open_date": "2026-07-09",
        "deadline": "2026-09-10",
        "budget": "Up to €500,000 per partner",
        "description": "Eurostars supports R&D-intensive SMEs in international collaborative projects. Slovakia is a member state. Call 11 cut-off: 10 September 2026, 14:00 CEST. Requires min. 2 partners from different EUREKA countries.",
        "url": "https://www.eurekanetwork.org/programmes-and-calls/eurostars/eurostars-call-for-projects-september-2026/",
        "tags": ["international", "consortium", "R&D"],
        "verified_on": "2026-08-26",
        "is_new": False,
        "closing_soon": False,
    },
]

# ── Merge and deduplicate ─────────────────────────────────────────────────────
def merge_opportunities(existing: list, fresh: list) -> tuple[list, list, list]:
    existing_ids = {o["id"] for o in existing}
    new_calls = []
    updated = list(existing)

    for o in fresh:
        if o["id"] not in existing_ids:
            o = {**o, "is_new": True}
            updated.append(o)
            new_calls.append(o)
        else:
            # Refresh all fields from source (deadline/budget/url/etc. may have
            # been corrected upstream) — only is_new status is preserved.
            for i, ex in enumerate(updated):
                if ex["id"] == o["id"]:
                    updated[i] = {**o, "is_new": ex.get("is_new", False)}
                    break

    # Mark closing soon
    closing = []
    today = datetime.now(timezone.utc)
    for o in updated:
        if o.get("deadline"):
            try:
                d = datetime.fromisoformat(o["deadline"])
                if d.tzinfo is None:
                    d = d.replace(tzinfo=timezone.utc)
                else:
                    d = d.astimezone(timezone.utc)
                days = (d - today).days
                o["closing_soon"] = 0 < days <= CLOSING_DAYS
                if o["closing_soon"]:
                    closing.append(o)
            except Exception:
                pass

    updated = drop_stale(updated)

    return updated, new_calls, closing

def drop_stale(opps: list) -> list:
    """Drop anything we can no longer vouch for.

    An entry survives only if it has a future deadline, or is explicitly marked
    rolling AND was re-confirmed within STALE_AFTER_DAYS. A blank deadline used
    to satisfy the old expiry check outright, which made such entries immortal —
    they stayed on the radar long after the programme behind them wound down.
    Every entry now has an expiry path: live API results are re-stamped on each
    run, so one that stops being listed ages out on its own.
    """
    kept = []
    for o in opps:
        deadline = (o.get("deadline") or "").strip()
        if deadline:
            if days_until(deadline) > 0:
                kept.append(o)
            else:
                print(f"  ⌛ expired, dropping: {o['id']} (deadline {deadline})")
            continue

        # No deadline: only rolling entries may stay, and only while fresh.
        if not o.get("rolling"):
            print(f"  ⚠ no deadline and not marked rolling, dropping: {o['id']}")
            continue

        age = days_since(o.get("verified_on", ""))
        if age > STALE_AFTER_DAYS:
            print(f"  ⚠ unverified for {age}d, dropping: {o['id']} — re-confirm and update verified_on")
            continue

        kept.append(o)
    return kept

# ── Email notification ────────────────────────────────────────────────────────
def send_email(new_calls: list, closing_calls: list):
    if not SMTP_USER or not SMTP_PASS:
        print("⚠ Email not configured (SMTP_USER/SMTP_PASS missing). Skipping.")
        return
    if not new_calls and not closing_calls:
        print("  No new or closing calls — skipping email.")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🇪🇺 Velgard Financing Radar — {datetime.now().strftime('%d %b %Y')}"
    msg["From"]    = SMTP_USER
    msg["To"]      = NOTIFY_EMAIL

    html = f"""
    <html><body style="font-family:Arial,sans-serif;background:#0f1117;color:#e2e8f0;padding:24px;max-width:700px;margin:0 auto">
    <div style="background:#1a1d27;border:1px solid #2e3350;border-radius:12px;padding:24px;margin-bottom:16px">
      <h1 style="color:#4f8ef7;margin:0 0 4px">🇪🇺 Velgard Financing Radar</h1>
      <p style="color:#8892a4;margin:0;font-size:13px">{datetime.now().strftime("%A, %d %B %Y")}</p>
    </div>
    """

    if new_calls:
        html += f"""
        <div style="background:#1a1d27;border:1px solid #2e3350;border-left:3px solid #22c55e;border-radius:12px;padding:20px;margin-bottom:16px">
          <h2 style="color:#22c55e;margin:0 0 16px;font-size:16px">✨ {len(new_calls)} New Call{"s" if len(new_calls)>1 else ""} Found</h2>
        """
        for o in new_calls:
            html += f"""
          <div style="margin-bottom:16px;padding:12px;background:#22263a;border-radius:8px">
            <div style="font-size:15px;font-weight:600;margin-bottom:4px">{o['title']}</div>
            <div style="font-size:12px;color:#8892a4;margin-bottom:6px">{o['programme']} · Deadline: {o['deadline']} · Budget: {o['budget']}</div>
            <div style="font-size:13px;color:#b4bcd0;margin-bottom:8px">{o['description'][:200]}...</div>
            <a href="{o['url']}" style="color:#4f8ef7;font-size:12px">Open call page ↗</a>
          </div>
            """
        html += "</div>"

    if closing_calls:
        html += f"""
        <div style="background:#1a1d27;border:1px solid #2e3350;border-left:3px solid #f59e0b;border-radius:12px;padding:20px;margin-bottom:16px">
          <h2 style="color:#f59e0b;margin:0 0 16px;font-size:16px">⏰ {len(closing_calls)} Call{"s" if len(closing_calls)>1 else ""} Closing Within 30 Days</h2>
        """
        for o in closing_calls:
            days = days_until(o["deadline"])
            html += f"""
          <div style="margin-bottom:16px;padding:12px;background:#22263a;border-radius:8px">
            <div style="font-size:15px;font-weight:600;margin-bottom:4px">{o['title']}</div>
            <div style="font-size:12px;color:#f59e0b;margin-bottom:6px">⏰ {days} days left — Deadline: {o['deadline']}</div>
            <a href="{o['url']}" style="color:#4f8ef7;font-size:12px">Open call page ↗</a>
          </div>
            """
        html += "</div>"

    html += """
    <p style="font-size:11px;color:#4a5568;text-align:center;margin-top:20px">
      Velgard Financing Radar · Auto-generated daily digest<br>
      <a href="https://velgard.github.io/finance-radar" style="color:#4f8ef7">Open dashboard</a>
    </p>
    </body></html>
    """

    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, NOTIFY_EMAIL, msg.as_string())
        print(f"✓ Email sent to {NOTIFY_EMAIL}")
    except Exception as e:
        print(f"⚠ Email send failed: {e}")

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print(f"\n{'─'*50}")
    print(f"Velgard Financing Radar — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'─'*50}\n")

    existing_data = load_existing()
    existing_opps = existing_data.get("opportunities", [])

    print("Fetching from sources...")
    fresh = []
    fresh += fetch_eu_portal()   # live API
    fresh += EIC_HARDCODED       # curated EIC calls
    fresh += NGI_CALLS           # NGI cascade
    fresh += SLOVAK_CALLS        # Slovak national calls
    fresh += OTHER_CALLS         # Eurostars, EUREKA

    print(f"\nMerging {len(fresh)} fetched with {len(existing_opps)} existing...")
    merged, new_calls, closing = merge_opportunities(existing_opps, fresh)

    print(f"  Total: {len(merged)} | New: {len(new_calls)} | Closing: {len(closing)}")

    save_data({"last_updated": "", "opportunities": merged})
    send_email(new_calls, closing)

    print("\n✓ Done.\n")

if __name__ == "__main__":
    main()
