// Generated by news_digest.py — 2026-03-29 08:00  [DEMO DATA]
window.NEWS_BADGES = {
  "Snyk": {
    "count": 2,
    "items": [
      {"title": "Snyk raises $150M Series G at $7.4B valuation", "url": "https://snyk.io/blog/"},
      {"title": "Snyk Code SAST now covers Go and Rust natively", "url": "https://snyk.io/blog/"}
    ]
  },
  "Detectify": {
    "count": 1,
    "items": [
      {"title": "Detectify launches new DAST module for GraphQL APIs", "url": "https://detectify.com/newsroom/"}
    ]
  },
  "Aikido Security": {
    "count": 3,
    "items": [
      {"title": "Aikido crosses $60M Series B at $1B valuation", "url": "https://www.aikido.dev/blog"},
      {"title": "New malware scanner added to Aikido platform", "url": "https://www.aikido.dev/blog"},
      {"title": "Aikido Security named Belgian unicorn of 2026", "url": "https://www.aikido.dev/blog"}
    ]
  },
  "SoSafe": {
    "count": 1,
    "items": [
      {"title": "SoSafe partners with Microsoft for Security Awareness", "url": "https://sosafe-awareness.com/newsroom/"}
    ]
  }
};
