#!/usr/bin/env python3
"""
Velgard European Financing Radar — Daily Fetch Script
Runs via GitHub Actions every morning.
Updates data/opportunities.json and sends email digest.
"""

import json
import os
import smtplib
import urllib.request
import urllib.parse
from datetime import datetime, timezone, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
NOTIFY_EMAIL   = "ivan.radvak@velgard.eu"
SMTP_HOST      = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT      = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER      = os.getenv("SMTP_USER", "")       # set as GitHub secret
SMTP_PASS      = os.getenv("SMTP_PASS", "")       # set as GitHub secret

KEYWORDS       = ["AI", "artificial intelligence", "cybersecurity", "cyber security",
                  "deep tech", "deeptech", "digital security", "machine learning",
                  "data security", "privacy", "encryption", "autonomous systems"]

DATA_FILE      = Path(__file__).parent.parent / "docs" / "data" / "opportunities.json"
DATA_JS_FILE   = Path(__file__).parent.parent / "docs" / "data" / "data.js"
CLOSING_DAYS   = 30   # flag as closing soon within N days

# ── Helpers ───────────────────────────────────────────────────────────────────
def days_until(date_str: str) -> int:
    d = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
    return (d.replace(tzinfo=timezone.utc) - datetime.now(timezone.utc)).days

def is_relevant(text: str) -> bool:
    text_lower = text.lower()
    return any(kw.lower() in text_lower for kw in KEYWORDS)

def load_existing() -> dict:
    if DATA_FILE.exists():
        with open(DATA_FILE) as f:
            return json.load(f)
    return {"last_updated": "", "opportunities": []}

def save_data(data: dict):
    data["last_updated"] = datetime.now(timezone.utc).isoformat()
    with open(DATA_FILE, "w") as f:
        json.dump(data, f, indent=2)
    # Also write data.js so index.html works when opened directly (file://)
    with open(DATA_JS_FILE, "w") as f:
        f.write("// Auto-generated by fetch_opportunities.py — do not edit manually\n")
        f.write("window.RADAR_DATA = ")
        json.dump(data, f, indent=2)
        f.write(";\n")
    print(f"✓ Saved {len(data['opportunities'])} opportunities")

# ── EU Funding & Tenders Portal ───────────────────────────────────────────────
def fetch_eu_portal() -> list:
    """
    EU Funding & Tenders public search API.
    Returns open calls matching Velgard keywords.
    """
    results = []
    url = "https://api.tech.ec.europa.eu/search-api/prod/rest/search"
    params = {
        "apiKey": "SEDIA",
        "text": "artificial intelligence cybersecurity deep tech",
        "pageSize": "50",
        "pageNumber": "1",
        "language": "en",
        "query": json.dumps({
            "bool": {
                "must": [
                    {"terms": {"status": ["31094501", "31094502"]}},  # open/forthcoming
                ]
            }
        }),
        "sort": json.dumps([{"field": "sortStatus", "order": "ASC"}, {"field": "deadlineDate", "order": "ASC"}])
    }

    try:
        req_url = url + "?" + urllib.parse.urlencode(params)
        req = urllib.request.Request(req_url, headers={"Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read())
            for item in data.get("results", []):
                md = item.get("metadata", {})
                title = first(md.get("title") or [])
                desc  = first(md.get("description") or [])

                if not is_relevant(title + " " + desc):
                    continue

                def first(lst, fallback=""):
                    return lst[0] if lst else fallback

                deadline_raw = first(md.get("deadlineDate") or [])
                deadline = deadline_raw[:10] if deadline_raw else ""
                open_date = first(md.get("startDate") or [])[:10]
                opp_id = first(md.get("identifier") or []) or item.get("id", "")
                url_path = f"https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/{opp_id}"

                # Detect EIC vs general Horizon
                programme = first(md.get("programmeName") or [], "Horizon Europe")
                source = "EIC" if "EIC" in programme else "EU Funding Portal"

                categories = []
                combined = (title + " " + desc).lower()
                if "artificial intelligence" in combined or " ai " in combined: categories.append("AI")
                if "cybersecurity" in combined or "cyber security" in combined: categories.append("cybersecurity")
                if "deep tech" in combined or "deeptech" in combined: categories.append("deep tech")
                if not categories: categories = ["deep tech"]

                results.append({
                    "id": opp_id,
                    "title": title,
                    "source": source,
                    "programme": programme,
                    "category": categories,
                    "status": "open",
                    "open_date": open_date,
                    "deadline": deadline,
                    "budget": first(md.get("budgetTopicAction") or [], "See call page"),
                    "description": desc[:400] + "..." if len(desc) > 400 else desc,
                    "url": url_path,
                    "tags": ["consortium", "EU"],
                    "is_new": False,
                    "closing_soon": False,
                })
    except Exception as e:
        print(f"⚠ EU Portal fetch error: {e}")

    print(f"  EU Portal: {len(results)} relevant results")
    return results

# ── EIC specific ──────────────────────────────────────────────────────────────
EIC_HARDCODED = [
    {
        "id": "EIC-ACCELERATOR-2026",
        "title": "EIC Accelerator 2026 — Open Call",
        "source": "EIC",
        "programme": "Horizon Europe — EIC",
        "category": ["AI", "cybersecurity", "deep tech"],
        "status": "open",
        "open_date": "2026-01-10",
        "deadline": "2026-10-01",
        "budget": "Up to €2.5M grant + €15M equity",
        "description": "EIC Accelerator supports individual SMEs and startups developing breakthrough innovations with high market potential. Open to all deep tech domains including AI, cybersecurity. Slovak companies fully eligible.",
        "url": "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
        "tags": ["SME", "startup", "equity", "blended finance"],
        "is_new": False,
        "closing_soon": False,
    },
    {
        "id": "EIC-PATHFINDER-OPEN-2026",
        "title": "EIC Pathfinder Open 2026",
        "source": "EIC",
        "programme": "Horizon Europe — EIC",
        "category": ["AI", "deep tech"],
        "status": "open",
        "open_date": "2026-01-15",
        "deadline": "2026-09-17",
        "budget": "Up to €3M",
        "description": "EIC Pathfinder Open funds visionary research into radically new technologies. No thematic restrictions. AI foundations, advanced security architectures, and novel computing paradigms are all eligible.",
        "url": "https://eic.ec.europa.eu/eic-funding-opportunities/eic-pathfinder_en",
        "tags": ["research", "early-stage", "TRL1-4"],
        "is_new": False,
        "closing_soon": False,
    },
]

# ── NGI Cascade calls ─────────────────────────────────────────────────────────
NGI_CALLS = [
    {
        "id": "NGI-TALER-2026-OC1",
        "title": "NGI Taler — Open Call for Privacy-Preserving Tech",
        "source": "Cascade",
        "programme": "NGI / Next Generation Internet",
        "category": ["cybersecurity", "deep tech"],
        "status": "open",
        "open_date": "2026-04-01",
        "deadline": "2026-07-31",
        "budget": "Up to €150,000",
        "description": "NGI Taler cascade grants for privacy-enhancing technologies, secure payment systems, and data sovereignty tools. Lightweight application, 3-month decision cycle.",
        "url": "https://ngi.eu/ngi-projects/ngi-taler/",
        "tags": ["cascade", "privacy", "fast-track"],
        "is_new": False,
        "closing_soon": False,
    },
    {
        "id": "NGI-SEARCH-OC3-2026",
        "title": "NGI Search — Open Call #3",
        "source": "Cascade",
        "programme": "NGI / Next Generation Internet",
        "category": ["AI", "deep tech"],
        "status": "open",
        "open_date": "2026-05-01",
        "deadline": "2026-07-15",
        "budget": "Up to €150,000",
        "description": "Third open call for SMEs and researchers working on next-generation search and AI-powered information retrieval. Velgard-relevant if you have AI/data sovereignty angle.",
        "url": "https://www.ngisearch.eu",
        "tags": ["cascade", "AI", "search"],
        "is_new": True,
        "closing_soon": True,
    },
]

# ── Slovak calls ──────────────────────────────────────────────────────────────
SLOVAK_CALLS = [
    {
        "id": "SIEA-INOVACIE-VOUCHERY-2026",
        "title": "Slovak Innovation Vouchers — SIEA 2026",
        "source": "Slovak",
        "programme": "Slovak OPII / OPIS 2021–2027",
        "category": ["AI", "deep tech"],
        "status": "open",
        "open_date": "2026-03-01",
        "deadline": "2026-12-31",
        "budget": "Up to €50,000",
        "description": "Innovation vouchers for Slovak SMEs to collaborate with research institutions on technological innovation, AI, and digital transformation. Rolling submission throughout 2026.",
        "url": "https://www.siea.sk/inovacne-vouchery/",
        "tags": ["Slovak", "SME", "voucher", "rolling"],
        "is_new": False,
        "closing_soon": False,
    },
    {
        "id": "SKIT-AI-SCALEUP-2026",
        "title": "SKIT — AI & Cybersecurity Scale-up Grant 2026",
        "source": "Slovak",
        "programme": "Slovak OPIS 2021–2027",
        "category": ["AI", "cybersecurity"],
        "status": "open",
        "open_date": "2026-04-15",
        "deadline": "2026-09-30",
        "budget": "€100,000–€500,000",
        "description": "SKIT supports Slovak deep tech startups scaling AI and cybersecurity products. Co-financing up to 85%. Eligible costs: R&D, hiring, market entry, IP protection.",
        "url": "https://www.skit.sk",
        "tags": ["Slovak", "startup", "co-financing", "scale-up"],
        "is_new": True,
        "closing_soon": False,
    },
]

# ── Other European calls ──────────────────────────────────────────────────────
OTHER_CALLS = [
    {
        "id": "EUROSTARS-2026-S2",
        "title": "Eurostars 2026/S2 — International R&D Collaboration",
        "source": "EU Funding Portal",
        "programme": "Eurostars / EUREKA",
        "category": ["AI", "cybersecurity", "deep tech"],
        "status": "open",
        "open_date": "2026-05-15",
        "deadline": "2026-09-04",
        "budget": "Up to €500,000 per partner",
        "description": "Eurostars supports R&D-intensive SMEs in international collaborative projects. Slovakia is member. AI, security, and deep tech projects are consistently funded. Requires min. 2 partners from different EUREKA countries.",
        "url": "https://www.eurekanetwork.org/eurostars",
        "tags": ["international", "consortium", "R&D"],
        "is_new": False,
        "closing_soon": False,
    },
    {
        "id": "EUREKA-GLOBALSTARS-2026",
        "title": "EUREKA GlobalStars — International Bilateral Calls",
        "source": "EU Funding Portal",
        "programme": "EUREKA",
        "category": ["AI", "deep tech"],
        "status": "open",
        "open_date": "2026-03-01",
        "deadline": "2026-10-30",
        "budget": "Varies by bilateral agreement",
        "description": "EUREKA GlobalStars provides R&D funding for collaborative projects between European and non-European partners (USA, Canada, South Korea, etc.). Good fit for Velgard if targeting global market entry.",
        "url": "https://www.eurekanetwork.org/funding/globalstars",
        "tags": ["international", "bilateral", "R&D"],
        "is_new": False,
        "closing_soon": False,
    },
]

# ── Merge and deduplicate ─────────────────────────────────────────────────────
def merge_opportunities(existing: list, fresh: list) -> tuple[list, list, list]:
    existing_ids = {o["id"] for o in existing}
    new_calls = []
    updated = list(existing)

    for o in fresh:
        if o["id"] not in existing_ids:
            o = {**o, "is_new": True}
            updated.append(o)
            new_calls.append(o)
        else:
            # Update closing_soon flag on existing entry
            for ex in updated:
                if ex["id"] == o["id"]:
                    ex["closing_soon"] = o.get("closing_soon", False)
                    break

    # Mark closing soon
    closing = []
    today = datetime.now(timezone.utc)
    for o in updated:
        if o.get("deadline"):
            try:
                d = datetime.fromisoformat(o["deadline"])
                if d.tzinfo is None:
                    d = d.replace(tzinfo=timezone.utc)
                else:
                    d = d.astimezone(timezone.utc)
                days = (d - today).days
                o["closing_soon"] = 0 < days <= CLOSING_DAYS
                if o["closing_soon"]:
                    closing.append(o)
            except Exception:
                pass

    # Remove expired
    updated = [o for o in updated if not o.get("deadline") or days_until(o["deadline"]) > 0]

    return updated, new_calls, closing

# ── Email notification ────────────────────────────────────────────────────────
def send_email(new_calls: list, closing_calls: list):
    if not SMTP_USER or not SMTP_PASS:
        print("⚠ Email not configured (SMTP_USER/SMTP_PASS missing). Skipping.")
        return
    if not new_calls and not closing_calls:
        print("  No new or closing calls — skipping email.")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🇪🇺 Velgard Financing Radar — {datetime.now().strftime('%d %b %Y')}"
    msg["From"]    = SMTP_USER
    msg["To"]      = NOTIFY_EMAIL

    html = f"""
    <html><body style="font-family:Arial,sans-serif;background:#0f1117;color:#e2e8f0;padding:24px;max-width:700px;margin:0 auto">
    <div style="background:#1a1d27;border:1px solid #2e3350;border-radius:12px;padding:24px;margin-bottom:16px">
      <h1 style="color:#4f8ef7;margin:0 0 4px">🇪🇺 Velgard Financing Radar</h1>
      <p style="color:#8892a4;margin:0;font-size:13px">{datetime.now().strftime("%A, %d %B %Y")}</p>
    </div>
    """

    if new_calls:
        html += f"""
        <div style="background:#1a1d27;border:1px solid #2e3350;border-left:3px solid #22c55e;border-radius:12px;padding:20px;margin-bottom:16px">
          <h2 style="color:#22c55e;margin:0 0 16px;font-size:16px">✨ {len(new_calls)} New Call{"s" if len(new_calls)>1 else ""} Found</h2>
        """
        for o in new_calls:
            html += f"""
          <div style="margin-bottom:16px;padding:12px;background:#22263a;border-radius:8px">
            <div style="font-size:15px;font-weight:600;margin-bottom:4px">{o['title']}</div>
            <div style="font-size:12px;color:#8892a4;margin-bottom:6px">{o['programme']} · Deadline: {o['deadline']} · Budget: {o['budget']}</div>
            <div style="font-size:13px;color:#b4bcd0;margin-bottom:8px">{o['description'][:200]}...</div>
            <a href="{o['url']}" style="color:#4f8ef7;font-size:12px">Open call page ↗</a>
          </div>
            """
        html += "</div>"

    if closing_calls:
        html += f"""
        <div style="background:#1a1d27;border:1px solid #2e3350;border-left:3px solid #f59e0b;border-radius:12px;padding:20px;margin-bottom:16px">
          <h2 style="color:#f59e0b;margin:0 0 16px;font-size:16px">⏰ {len(closing_calls)} Call{"s" if len(closing_calls)>1 else ""} Closing Within 30 Days</h2>
        """
        for o in closing_calls:
            days = days_until(o["deadline"])
            html += f"""
          <div style="margin-bottom:16px;padding:12px;background:#22263a;border-radius:8px">
            <div style="font-size:15px;font-weight:600;margin-bottom:4px">{o['title']}</div>
            <div style="font-size:12px;color:#f59e0b;margin-bottom:6px">⏰ {days} days left — Deadline: {o['deadline']}</div>
            <a href="{o['url']}" style="color:#4f8ef7;font-size:12px">Open call page ↗</a>
          </div>
            """
        html += "</div>"

    html += """
    <p style="font-size:11px;color:#4a5568;text-align:center;margin-top:20px">
      Velgard Financing Radar · Auto-generated daily digest<br>
      <a href="https://velgard.github.io/finance-radar" style="color:#4f8ef7">Open dashboard</a>
    </p>
    </body></html>
    """

    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, NOTIFY_EMAIL, msg.as_string())
        print(f"✓ Email sent to {NOTIFY_EMAIL}")
    except Exception as e:
        print(f"⚠ Email send failed: {e}")

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print(f"\n{'─'*50}")
    print(f"Velgard Financing Radar — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'─'*50}\n")

    existing_data = load_existing()
    existing_opps = existing_data.get("opportunities", [])

    print("Fetching from sources...")
    fresh = []
    fresh += fetch_eu_portal()   # live API
    fresh += EIC_HARDCODED       # curated EIC calls
    fresh += NGI_CALLS           # NGI cascade
    fresh += SLOVAK_CALLS        # Slovak national calls
    fresh += OTHER_CALLS         # Eurostars, EUREKA

    print(f"\nMerging {len(fresh)} fetched with {len(existing_opps)} existing...")
    merged, new_calls, closing = merge_opportunities(existing_opps, fresh)

    print(f"  Total: {len(merged)} | New: {len(new_calls)} | Closing: {len(closing)}")

    save_data({"last_updated": "", "opportunities": merged})
    send_email(new_calls, closing)

    print("\n✓ Done.\n")

if __name__ == "__main__":
    main()
